### DISCUSSION TITLE
Strange cuda error for larger batch sizes.

### DISCUSSION THREAD

**Discussion by Binbose** [jax-ml/jax#13342] [Q&A] [answered]
I am trying to code a continuous normalizing flow in jax (the code is quite lengthy, but I can paste it here if needed). When I train with a small enough batch_size (e.g. 128) it trains without throwing errors. However, when I increase the batch size, I get this strange error. I was wondering if anybody encountered this before and could hint me to why this might be happening:

```
Traceback (most recent call last):
  File "/home/luca/Projects/CWF/cwf.py", line 227, in <module>
    train(rng, config, reference_, 2, 32, 0., 1., visual=True)
  File "/home/luca/Projects/CWF/cwf.py", line 116, in train
    state, loss = train_step(state, batch, reference, in_out_dim, hidden_dim, t0, t1)
  File "/home/luca/anaconda3/envs/CWF/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/luca/anaconda3/envs/CWF/lib/python3.10/site-packages/jax/_src/api.py", line 621, in cache_miss
    out_flat = call_bind_continuation(execute(*args_flat))
  File "/home/luca/anaconda3/envs/CWF/lib/python3.10/site-packages/jax/_src/dispatch.py", line 895, in _execute_compiled
    out_flat = compiled.execute(in_flat)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to complete all kernels launched on stream 0x3acaae0: stream did not block host until done; was already in an error state
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/luca/anaconda3/envs/CWF/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/luca/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/luca/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/luca/Projects/CWF/cwf.py", line 227, in <module>
    train(rng, config, reference_, 2, 32, 0., 1., visual=True)
  File "/home/luca/Projects/CWF/cwf.py", line 116, in train
    state, loss = train_step(state, batch, reference, in_out_dim, hidden_dim, t0, t1)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to complete all kernels launched on stream 0x3acaae0: stream did not block host until done; was already in an error state
2022-11-21 18:11:54.386920: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:1032] could not wait stream on event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2022-11-21 18:11:54.386970: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/stream.cc:1049] Error waiting for event in stream: error recording waiting for CUDA event on stream 0x3b5a230; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2022-11-21 18:11:54.386985: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:1159] failed to enqueue async memcpy from device to host: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; host dst: 0x7fee84002140; GPU src: 0x7fef08000400; size: 2048=0x800
2022-11-21 18:11:54.386996: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/stream.cc:321] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2022-11-21 18:11:54.387006: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:614] unable to add host callback: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2022-11-21 18:11:54.387389: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:1032] could not wait stream on event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2022-11-21 18:11:54.387427: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/stream.cc:1049] Error waiting for event in stream: error recording waiting for CUDA event on stream 0x3b5a500; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2022-11-21 18:11:54.387438: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:1159] failed to enqueue async memcpy from device to host: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; host dst: 0x7feed40028d0; GPU src: 0x7fef08000200; size: 8=0x8
2022-11-21 18:11:54.387448: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/stream.cc:321] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2022-11-21 18:11:54.387458: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:614] unable to add host callback: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2022-11-21 18:11:54.387897: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:1032] could not wait stream on event: CUD:54.387920: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/stream.cc:1049] Error waiting for event in stream: error recording waiting for CUDA event on stream 0x3b59c90; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2022-11-21 18:11:54.387932: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:1159] failed to enqueue async memcpy from device to host: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; host dst: 0x7fee84002980; GPU src: 0x7fef08000300; size: 8=0x8
2022-11-21 18:11:54.387943: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/stream.cc:321] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2022-11-21 18:11:54.387952: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:614] unable to add host callback: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encounteredA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2022-11-21 18:11:54.387920: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/stream.cc:1049] Error waiting for event in stream: error recording waiting for CUDA event on stream 0x3b59c90; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2022-11-21 18:11:54.387932: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:1159] failed to enqueue async memcpy from device to host: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; host dst: 0x7fee84002980; GPU src: 0x7fef08000300; size: 8=0x8
2022-11-21 18:11:54.387943: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/stream.cc:321] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2022-11-21 18:11:54.387952: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:614] unable to add host callback: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

**Comment by hawkinsp** [comment]
`CUDA_ERROR_ILLEGAL_ADDRESS` sounds like a bug in either XLA or one of NVIDIA's libraries. We'll need a reproduction of the problem and details of your GPU and CUDA version to debug, though. Please file a bug with those details?

**Comment by Binbose** [comment, marked as answer]
Mh, I solved it; it seems to have been some weird error arising from wrong reshaping and differentiating, probably not an underlying bug in cuda. I will file a bug report if it comes up again.

**Reply by hawkinsp** [reply]
`CUDA_ERROR_ILLEGAL_ADDRESS` is likely always a bug in JAX, not your code. If you see it again, please file a bug.
