### ISSUE TITLE
0.6 Installation issues and 0.5 segfaults

### ISSUE THREAD

**Issue by GJBoth** [jax-ml/jax#28623]
### Description

I'm getting CUDNN errors under Jax 0.6.0:

```E0508 14:21:35.604286  183162 cuda_dnn.cc:520] Loaded runtime CuDNN library: 9.4.0 but source was compiled with: 9.8.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.```

I'm confused about this, as I was under the impression that Jax bundles it's own CuDNN since somewhere in the 0.4's. The right version seems to be installed though:`nvidia-cudnn-cu12: 9.10.0.56`

There's an interesting part 2 to the problem though. When I try installing `0.5.3` I run segfault issues when calling `jnp.fft.ifft`. My observations are:
1) I can install jax `0.5.3` on our A100 nodes - this install the following nvidia dependencies, and works fine:  
```
"nvidia-cublas-cu12==12.8.4.1",
"nvidia-cuda-cupti-cu12==12.8.90",
"nvidia-cuda-nvcc-cu12==12.8.93",
"nvidia-cuda-runtime-cu12==12.8.90",
"nvidia-cudnn-cu12==9.8.0.87",
"nvidia-cufft-cu12==11.3.3.83",
"nvidia-cusolver-cu12==11.7.3.90",
"nvidia-cusparse-cu12==12.5.8.93",
"nvidia-nccl-cu12==2.26.2",
"nvidia-nvjitlink-cu12==12.8.93",
```

2) When I do the same on our H200 nodes, this is what gets installed, and when I get segfaults running `jnp.fft.ifft`:
```
nvidia-cublas-cu12       12.9.0.13
nvidia-cuda-cupti-cu12   12.9.19
nvidia-cuda-nvcc-cu12    12.9.41
nvidia-cuda-runtime-cu12 12.9.37
nvidia-cudnn-cu12        9.10.0.56
nvidia-cufft-cu12        11.4.0.6
nvidia-cusolver-cu12     11.7.4.40
nvidia-cusparse-cu12     12.5.9.5
nvidia-nccl-cu12         2.26.5
nvidia-nvjitlink-cu12    12.9.41
```

You can see that it installs cuda 12.9 instead of 12.8, even though my nvidia-smi cuda version is 12.8. Could this be causing the segfaults? Why is Jax trying to install 12.9?

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.6.0
jaxlib: 0.6.0
numpy:  2.2.5
python: 3.12.5 (main, Aug 14 2024, 05:08:31) [Clang 18.1.8 ]
device info: NVIDIA H200-1, 1 local devices"
process_count: 1
platform: uname_result(system='Linux', node='h05u32.int.janelia.org', release='5.14.0-362.8.1.el9_3.x86_64', version='#1 SMP PREEMPT_DYNAMIC Wed Nov 8 17:36:32 UTC 2023', machine='x86_64')

**Comment by ZacCranko** [comment]
Can you confirm the issue persists if you're installing JAX via `pip install jax[cuda12]`?

**Comment by GJBoth** [comment]
Tried on multiple nodes; directly `pip` and using `uv` - the issue keeps popping up.

**Comment by hawkinsp** [comment]
` Loaded runtime CuDNN library: 9.4.0 but source was compiled with: 9.8.0.` means that JAX is finding another installation of cudnn. Two things to check:

`pip freeze | grep nvidia`: is the correct version actually installed? My guess is that some other package has overridden our version and you have an old version installed. Share the output of this comment?

Is there another copy somewhere in your `LD_LIBRARY_PATH`?

**Comment by takkyu2** [comment]
Just to add one more data point, we have also encountered segfault with both jax v0.6 and v0.5 on H100.

## Minimal Reproduction Example 
```python
from flax import nnx
import jax.numpy as jnp

rngs = nnx.Rngs(0)
x = jnp.ones((1, 8, 3))
layer = nnx.Conv(in_features=3, out_features=4, kernel_size=(3,), padding='VALID', rngs=rngs)
out = layer(x)
```

## v0.6 jax info (leading to segfault)
```
jax:    0.6.0
jaxlib: 0.6.0
numpy:  2.2.5
python: 3.10.9 (main, Jan 16 2023, 22:37:31) [Clang 15.0.7 ]
device info: NVIDIA H100 80GB HBM3-1, 1 local devices"
process_count: 1
platform: uname_result(system='Linux', node='XXX, release='XXX', version='#18-Ubuntu SMP Fri Jul 26 14:21:24 UTC 2024', machine='x86_64')
```

## v0.5 jax info (leading to segfault)
```
jax:    0.5.3
jaxlib: 0.5.3
numpy:  2.2.5
python: 3.10.9 (main, Jan 16 2023, 22:37:31) [Clang 15.0.7 ]
device info: NVIDIA H100 80GB HBM3-1, 1 local devices"
process_count: 1
platform: uname_result(system='Linux', node='XXX', release='XXX', version='#18-Ubuntu SMP Fri Jul 26 14:21:24 UTC 2024', machine='x86_64')
```

## Workaround
The workaround is either
1. set `LD_LIBRARY_PATH` to be empty
1. specify the `nvidia-cublas-cu12` version to be strictly less than 12.9 as (Thank you @GJBoth for pointing out the package dependency problem):
```
uv add "nvidia-cublas-cu12<12.9"
```

Using one of these workarounds resolved segfault. I suspect there might be some breaking change in cublas 12.9?

As I understand it, setting `LD_LIBRARY_PATH` to be empty is not be required since [0.4.19](https://docs.jax.dev/en/latest/changelog.html#jaxlib-0-4-19-oct-19-2023); Since some users may want to use both torch and jax, setting `LD_LIBRARY_PATH` might be a bit inconvenient in some use cases.

**Comment by GJBoth** [comment]
@hawkinsp When I removed `LD_LIBRARY_PATH` it indeed fixed the issue - 0.6.0 now runs! Remarkably, I'd set it quite a while ago and everything ran fine; did it only now give errors because 0.6 updated it's CuDNN version?

More confusingly, the segfaults have now been solved as well on `0.5.3` as well when using "nvidia-cublas-cu12==12.9". What I fail to understand is *why* - if it bypassed the jax-bundled cuda (as with `0.6.0`) and used the system one, why did setting "nvidia-cublas-cu12==12.8" get rid of the segfaults? Or do we just assign this to cuda black magic?

**Comment by hawkinsp** [comment]
Closing on the assumption this is stale: these versions are quite old.
