### ISSUE TITLE
On import of package using jax: "jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details"

### ISSUE THREAD

**Issue by TiernonRR** [jax-ml/jax#28752]
### Description

When I import a package (i.e. import keypoint_moseq) that itself uses jax, I receive an error initializing DNN library. Here is the full traceback:

```
E0514 15:42:22.522887 3766360 cuda_dnn.cc:532] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E0514 15:42:22.536489 3766360 cuda_dnn.cc:536] Memory usage: 16601251840 bytes free, 16928342016 bytes total.
E0514 15:42:22.584472 3766360 cuda_dnn.cc:532] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E0514 15:42:22.584506 3766360 cuda_dnn.cc:536] Memory usage: 16601251840 bytes free, 16928342016 bytes total.
E0514 15:42:29.663750 3766360 cuda_dnn.cc:532] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E0514 15:42:29.663801 3766360 cuda_dnn.cc:536] Memory usage: 16601251840 bytes free, 16928342016 bytes total.
E0514 15:42:30.745147 3766360 cuda_dnn.cc:532] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E0514 15:42:30.745224 3766360 cuda_dnn.cc:536] Memory usage: 16601251840 bytes free, 16928342016 bytes total.
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/keypoint_moseq/__init__.py", line 11, in <module>
    from .io import *
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/keypoint_moseq/io.py", line 19, in <module>
    from keypoint_moseq.util import list_files_with_exts, check_nan_proportions
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/keypoint_moseq/util.py", line 14, in <module>
    from jax_moseq.models.keypoint_slds import inverse_rigid_transform
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax_moseq/__init__.py", line 2, in <module>
    from . import models
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax_moseq/models/__init__.py", line 1, in <module>
    from . import arhmm
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax_moseq/models/arhmm/__init__.py", line 1, in <module>
    from jax_moseq.models.arhmm.initialize import *
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax_moseq/models/arhmm/initialize.py", line 7, in <module>
    from jax_moseq.utils.distributions import sample_mniw
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax_moseq/utils/distributions.py", line 5, in <module>
    from dynamax.hidden_markov_model.inference import hmm_posterior_sample
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/dynamax/hidden_markov_model/__init__.py", line 1, in <module>
    from dynamax.hidden_markov_model.models.abstractions import HMM, HMMEmissions, HMMInitialState, HMMTransitions, HMMParameterSet, HMMPropertySet
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/dynamax/hidden_markov_model/models/abstractions.py", line 7, in <module>
    from dynamax.ssm import SSM
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/dynamax/ssm.py", line 22, in <module>
    from dynamax.utils.optimize import run_sgd
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/dynamax/utils/optimize.py", line 32, in <module>
    key=jr.PRNGKey(0)):
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/random.py", line 248, in PRNGKey
    return _return_prng_keys(True, _key('PRNGKey', seed, impl))
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/random.py", line 200, in _key
    return prng.random_seed(seed, impl=impl)
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/prng.py", line 548, in random_seed
    seeds_arr = jnp.asarray(np.int64(seeds))
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 5714, in asarray
    return array(a, dtype=dtype, copy=bool(copy), order=order, device=device)
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 5548, in array
    out_array: Array = lax_internal._convert_element_type(
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 1727, in _convert_element_type
    return convert_element_type_p.bind(
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/core.py", line 496, in bind
    return self._true_bind(*args, **params)
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/core.py", line 512, in _true_bind
    return self.bind_with_trace(prev_trace, args, params)
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 4875, in _convert_element_type_bind_with_trace
    operand = core.Primitive.bind_with_trace(convert_element_type_p, trace, args, params)
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/core.py", line 517, in bind_with_trace
    return trace.process_primitive(self, args, params)
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/core.py", line 1017, in process_primitive
    return primitive.impl(*args, **params)
  File "/storage/home/hcoda1/3/triesenmy3/p-jmarkowitz30-0/miniconda3/envs/keypmoseq_gpu/lib/python3.10/site-packages/jax/_src/dispatch.py", line 89, in apply_primitive
    outs = fun(*args)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

The issue seems to arise in an import that calls jr.PRNGKey(0). Thank you in advance!

### System info (python version, jaxlib version, accelerator, etc.)

Here is the output from `import jax; jax.print_environment_info()`

```
jax:    0.6.0
jaxlib: 0.6.0
numpy:  1.26.4
python: 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0]
device info: Tesla V100-PCIE-16GB-1, 1 local devices"
process_count: 1
platform: uname_result(system='Linux', node='atl1-1-02-005-29-0.pace.gatech.edu', release='5.14.0-503.35.1.el9_5.x86_64', version='#1 SMP PREEMPT_DYNAMIC Mon Mar 24 11:15:27 EDT 2025', machine='x86_64')


$ nvidia-smi
Wed May 14 15:47:28 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.06             Driver Version: 570.124.06     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100-PCIE-16GB           On  |   00000000:AF:00.0 Off |                    0 |
| N/A   46C    P0             42W /  250W |     312MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A         3766360      C   python                                  308MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by dfm** [comment]
This is normally caused by a broken installation. You might try reinstalling JAX in a fresh environment using `pip install jax[cuda12]`, and checking to see if there are other CUDA installations on your system. If you're not able to work out what's going on and try a clean install, please report back and we'll see if we can help you debug!

**Comment by TiernonRR** [comment]
@dfm Thank you for your quick reply! I just tried a clean env with `pip install jax[cuda12]` but this produced the same error. I took a look in the /usr/local/ directory and found

```
lrwxrwxrwx.  1 root root   22 May  5 07:48 cuda -> /etc/alternatives/cuda
lrwxrwxrwx.  1 root root   25 May  5 07:48 cuda-12 -> /etc/alternatives/cuda-12
drwxr-xr-x.  4 root root   29 May  5 14:55 cuda-12.5

```

Is this what you are referring to in regards to "other CUDA installations" on the system? Also, to note that when I run `echo $LD_LIBRARY_PATH` in the terminal, cuda is nowhere to be found. Thanks again!

**Comment by rohandekate10** [comment]
I get the same error.
Do you get a message like this?
`Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.8.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.`

**Comment by TiernonRR** [comment]
@rohandekate10 I have not gotten this error. Still trying to figure out my issue to no avail.

**Comment by TiernonRR** [comment]
@rohandekate10 I was able to solve this. I deprecated jax to 0.4.36 as this was compiled with cudnn that is available on conda. I suppose you could also download cudnn from nvida, but this seems like the simpler solution.
