### ISSUE TITLE
FFI breaks if sm_90a is targeted

### ISSUE THREAD

**Issue by bmac3** [jax-ml/jax#29148]
### Description

Hello,
I'm trying to write a foreign function in JAX using CUDA and CUTLASS, but I'm running into an issue with the FFI module. If I try to compile my code with [architecture specific features](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#architecture-specific-features) (i.e. setting the compute capability to 90a instead of 90), I get the error `jaxlib._jax.XlaRuntimeError: INTERNAL: CUDA error: a PTX JIT compilation failed`. The architecture specific features are need for the CUTLASS library (see the Target Architecture section [here](https://docs.nvidia.com/cutlass/overview.html#target-architecture)) to run certain TMA and wgmma commands among other things. I've compiled a minimal example [here](https://github.com/bmac3/jax-ffi/tree/main) based on the [jax/examples/ffi](https://github.com/jax-ml/jax/tree/main/examples/ffi/) examples. I was wondering if there is something that needs to be done when setting up the ffi function or if compiling with architecture specific feature sets is currently unsupported by ffi.

Other references:
I notice that this [jax flash-attention-3 binding](https://github.com/kyutai-labs/jax-flash-attn3/tree/main) was compiled with sm_90a but they don't use ffi.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.6.1
jaxlib: 0.6.1
numpy:  2.1.3
python: 3.11.12 (main, Apr  9 2025, 08:55:55) [GCC 13.3.0]
device info: NVIDIA GeForce RTX 5090-1, 1 local devices"
process_count: 1
platform: uname_result(system='Linux', node='54ca38454761', release='6.8.0-57-generic', version='#59~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Mar 19 17:07:41 UTC 2', machine='x86_64')

$ nvidia-smi
Sat May 31 22:31:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.133.07             Driver Version: 570.133.07     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5090        On  |   00000000:61:00.0 Off |                  N/A |
|  0%   46C    P1             29W /  600W |     525MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A          159161      C   python                                  516MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by dfm** [comment]
Huh! There shouldn't be any FFI-specific issues here. That error is being raised in "your" code here:

https://github.com/bmac3/jax-ffi/blob/34f1be7dbe7b6dafb9bc3f854a31d5034490b51d/src/jax_ffi_example/cuda_examples.cu#L59-L63

So I don't think it's really related to the FFI. You might try using the same build system and making sure that you can execute a kernel like without using the FFI using the same flags, etc. There could well be some CMake-specific tuning that is required, but I must admit that I'm not totally familiar with all the relevant considerations! If everything works as expected in that experiment, please report back and I'll see if I can narrow it down over here.

**Comment by bmac3** [comment]
Ok I took your suggestion and it looks like you're right, when I used the [old way of extending jax](https://github.com/dfm/extending-jax/tree/371dca93c6405368fa8e71690afd3968d75f4bac) (thank you for that repo btw) I found that I got the same error. I think the problem probably has to do with CMake-specific stuff like you were mentioning. Thanks so much for the help! I will close this for now.

**Comment by bmac3** [comment]
For anyone interested, it turned out that I was making a silly mistake. I was trying to run sm_90a code on a 5090, which means I was running Hopper specific code on a Blackwell GPU.
