### ISSUE TITLE
building jax 0.7.2 from source fails on Jetson Orin Nano

### ISSUE THREAD

**Issue by notnot** [jax-ml/jax#32166]
### Description

I tried to install jax on my Jetson Orin Nano, first in the usual way with 'pip install "jax[cuda12]". It seemed to work well but when running a script that trains a simple small network i get an error: CUDA Runtime error:
[0] Failed call to cudaGetFuncBySymbol: cudaErrorKernelImageForDevice: no kernel
image is available for execution on the device.

So i tried to build jax from source, at first with default settings:
python build/build.py build --wheels=jaxlib,jax-cuda-plugin,jax-cuda-pjrt
This produced the 3 wheels fine, and after installing these, and jax itself, i tried to run my small network again.
It gave a different error: a CUDNN version mismatch. 
I then tried a new build with --cudnn_version=9.3.0 (which is present on my system). This froze up my machine.

I googled a lot and found some tips. My last attempt was to be as specific as possible:
(venv) jax$ python build/build.py build --wheels=jaxlib,jax-cuda-plugin,jax-cuda-pjrt --cuda_version=12.6.0 --cudnn_version=9.3.0 --cuda_compute_capabilities=sm_87

This build failed with this error:
ERROR: /home/jpad/prog/jax/jax/jaxlib/cuda/BUILD:175:11: Compiling jaxlib/gpu/solver_kernels_ffi.cc failed: (Exit 1): nvcc_wrapper failed: error executing CppCompile command (from target //jaxlib/cuda:cusolver_kernels_ffi)

I can give the full output here if necessary.
I am frustrated after spending two days on this (a build of jax on the Jetson Orin Nano takes several hours).
If someone can provide a wheel for this system with a fairly recent jax[cuda12] i'd be grateful!

### System info (python version, jaxlib version, accelerator, etc.)

I can't provide jax info because it is not working right now.

System: Jetson Orin Nano 8GB
jetpack 6.1, cuda 12.6.0, cudnn 9.3.0, compute capability sm_87

**Comment by rdyro** [comment]
Trying to build the cuda plugin can be frustrating, can you try building with clang:

```
python build/build.py build --wheels=jaxlib,jax-cuda-plugin,jax-cuda-pjrt --bazel_options=--copt=-Wno-c23-extensions --build_cuda_with_clang 
```

**Comment by notnot** [comment]
Yes, today i had a look on the machine and discovered that is does not have clang installed. I skipped over that part in the jax from source installation guide too easily. When i have time, it will be the first thing i try: install clang and give the build another go.

**Comment by notnot** [comment]
Create a virtual environment for this quest, to be safe!
I have tried various versions of jax/jaxlib, and the first one that worked was jax 0.5.3, after a week of stressful evenings. Perhaps later versions will also work, once the infrastructure is set up properly. Maybe i'll try those at a later time. For now the good news is that i have a working JAX & FLAX on the Jetson Orin Nano!

Open the JAX 'build from source' documentation as a reference.

Build jaxlib with this command:
`python build/build.py build --wheels=jaxlib,jax-cuda-plugin,jax-cuda-pjrt --cuda_version=12.6.0 --cudnn_version=9.3.0 --cuda_compute_capabilities=sm_87`

Providing the versions is necessary otherwise you will get version mismatch errors.

The default gcc g++ compiler on jetpack 6.1 is not able to compile the jaxlib sources without errors. 

Install clang:
	`sudo apt install clang`

Install libstdc++, because clang will give some #include file not found errors:
	`sudo apt install libstdc++-12-dev`

It turns out that clang v17 is the minimal version required, because it can handle ARM SVE properly. Earlier
compilers, like v14 will exit with a SVE related error. Upgrade clang to v17:

```
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh 17
```

Make clang v17 the default (this version handles Arm SVE properly)

```
sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 100
sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 100
```

The jaxlib build now finish without errors, but after installing 
```
pip install dist/*.whl
pip install -e .
```

Sadly you get runtime errors regarding cublas, which can't be found when running scripts that use jax. It turns out that the Nano does not have LD_LIBRARY_PATH set! I updated ~/.profile to set it so it includes the directory where the nvidia cuda libraries live.

```
echo $LD_LIBRARY_PATH
:/usr/local/cuda-12.6/lib64
```

This makes the nvidia libraries findable for the build system. The runtime error disappeared after a new build with the LD_LIBRARY_PATH.

By the way: in your virtual environment, don't install the cuda-tools via pip, at least not the current version,
because they will lead to hard to debug segmentation faults, even if the build went fine and there are no longer any runtime errors.

Test your JAX. 
If it works proceed with installing FLAX and friends but beware of their versions. Installing the current FLAX will wipe out your custom jax and replace it with a version that will not work on the Jetson Orin :( I figured out the dependencies of all packages needed, via their releases on github.com, checking their pyproject.toml files. I came to this order of installing that works, and leaves your self-built jax as it is:

```
jax-jax-v0.5.3$ pip install chex==0.1.90
jax-jax-v0.5.3$ pip install orbax-checkpoint==0.11.0
jax-jax-v0.5.3$ pip install optax==0.2.5
jax-jax-v0.5.3$ pip install flax==0.10.0
```

Once you are satisfied with your jax install, you might want to install it permanently, so that is
is no longer dependent on the presence of the jax source code on your system:

```
jax-jax-v0.5.3$ pip uninstall jax
jax-jax-v0.5.3$ pip install .
```

I hope this information will be of help to any of you in a similar situation. This was my first true confrontation with dependency hell, and it is not pleasant. You do learn a few things in the meantime though :)

**Comment by rdyro** [comment]
Awesome, thanks so much for detailing the steps!

**Comment by notnot** [comment]
I can confirm that building jax 0.6.0 from source also works using the above guidelines.
